# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
env:
 global:
   - CRAN: http://cran.rstudio.com
   
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - ./travis-tool.sh install_deps
